# -*- coding: utf-8 -*-
"""Bi-Level_HOAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16HSad7cAkL5TeSoDHeRb1513qaOjNrC5
"""

import matplotlib.pyplot as plt
import torch

print("Generating visualizations using your optimized physics regularizer...")

model_joint.eval()

# Take one batch of unseen test data
test_iterator = iter(test_loader)
y_batch, img_batch, label_batch = next(test_iterator)

# Visualize the first 3 images from this batch
num_images_to_show = 3

fig, axes = plt.subplots(num_images_to_show, 3, figsize=(12, 4 * num_images_to_show))

for i in range(num_images_to_show):
    # 1. Extract a single image and its degraded measurement
    y = y_batch[i:i+1].to(Config.DEVICE)
    img = img_batch[i:i+1].to(Config.DEVICE)
    true_label = label_batch[i].item()

    # 2. Reconstruct the image using your learned physics parameters (theta)
    # We take 400 steps to let the pixels perfectly settle into the loss valley
    w_init = physics.A_dagger(y).detach().clone().clamp(0, 1)
    w_star = solve_inner_problem(w_init, theta, y, physics, inner_loss_func,
                                 hoag_state, Config.INNER_LR, Config.INNER_STEPS)

    # 3. Classify the reconstructed image
    with torch.no_grad():
        prediction = model_joint(w_star.clamp(0, 1)).argmax(dim=1).item()

    # Convert the PyTorch tensors back into standard arrays
    orig_np = img.squeeze().cpu().numpy()
    blur_np = y.squeeze().cpu().numpy()
    recon_np = w_star.squeeze().detach().cpu().numpy()

    # --- Plotting ---

    # Left Column: Ground Truth
    axes[i, 0].imshow(orig_np, cmap='gray')
    axes[i, 0].set_title(f"Ground Truth\n", fontsize=14)
    axes[i, 0].axis('off')

    # Middle Column: Degraded Measurement
    axes[i, 1].imshow(blur_np, cmap='gray')
    axes[i, 1].set_title("Degraded Measurement\n", fontsize=14)
    axes[i, 1].axis('off')

    # Right Column: The Bilevel Reconstruction
    axes[i, 2].imshow(recon_np, cmap='gray')

    color = 'green' if prediction == true_label else 'red'
    axes[i, 2].set_title(f"Reconstructed Image\n", fontsize=14, color=color)
    axes[i, 2].axis('off')

plt.tight_layout()
plt.show()

import os
import sys
import time
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.autograd as autograd
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt

# ==========================================
# 1. CONFIGURATION
# ==========================================
class Config:
    DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    # --- Dataset constraints ---
    SUBSET_SIZE = 100  # Strictly 100 images as requested

    # --- Physical Degradation ---
    IMG_SIZE = 28
    BLUR_SIGMA = 3.0
    NOISE_SIGMA = 0.01

    # --- Hyperparameters ---
    EPOCHS = 30         # INCREASED to 30 for full visual convergence
    INNER_STEPS = 400   # High steps to guarantee lower-level convergence for IFT
    LR_THETA = 0.05     # Meta-learning rate for the regularizer
    INNER_LR = 0.05

    # --- HOAG specific ---
    HOAG_EPSILON_TOL_INIT = 1e-3
    HOAG_TOLERANCE_DECREASE = 'exponential'
    HOAG_DECREASE_FACTOR = 0.9
    HOAG_CG_MAX_ITER = 50

# ==========================================
# 2. PHYSICS & LOSS
# ==========================================
def get_gaussian_kernel_2d(k_size, sig):
    coords = torch.arange(k_size, dtype=torch.float32) - (k_size - 1) / 2
    Y, X = torch.meshgrid(coords, coords, indexing='ij')
    squared_dist = X**2 + Y**2
    g_2d = torch.exp(-squared_dist / (2 * sig**2))
    return (g_2d / g_2d.sum()).view(1, 1, k_size, k_size).to(Config.DEVICE)

class Physics2D:
    def __init__(self, blur_sigma, noise_sigma, device):
        # FIXED: Matched the paper's exact physics configuration
        self.k_size = 23
        self.padding = self.k_size // 2
        self.kernel = get_gaussian_kernel_2d(self.k_size, blur_sigma).to(device)
        self.noise_sigma = noise_sigma

    def A(self, x):
        padded = F.pad(x, [self.padding]*4, mode='constant', value=0)
        return F.conv2d(padded, self.kernel)

    def A_adjoint(self, y):
        return F.conv_transpose2d(y, self.kernel, padding=self.padding)

    def A_dagger(self, y):
        return y.clone()

    def __call__(self, x):
        return self.A(x) + torch.randn_like(self.A(x)) * self.noise_sigma

def regularizer_only(w, theta):
    theta_0, theta_1 = theta[0], theta[1]
    dh = w[:, :, :, 1:] - w[:, :, :, :-1]
    dv = w[:, :, 1:, :] - w[:, :, :-1, :]
    dh = F.pad(dh, (0, 1, 0, 0))
    dv = F.pad(dv, (0, 0, 0, 1))
    tv_norm = torch.sqrt(dh**2 + dv**2 + torch.exp(theta_1))
    return (torch.exp(theta_0) / w.numel()) * tv_norm.sum()

def inner_loss_func(w, theta, y, physics_op):
    Aw = physics_op.A(w)
    n = y.numel()
    fidelity = (1.0 / n) * torch.sum((y - Aw)**2)
    return fidelity + regularizer_only(w, theta)

# ==========================================
# 3. DATASET
# ==========================================
class BlurMNISTDataset(Dataset):
    def __init__(self, physics, train=True, subset_size=None):
        self.physics = physics
        self.dataset = torchvision.datasets.MNIST(
            root='./data', train=train, download=True,
            transform=transforms.Compose([transforms.ToTensor()]))
        if subset_size is not None:
            self.dataset = torch.utils.data.Subset(self.dataset, list(range(subset_size)))

    def __len__(self):
        return len(self.dataset)

    def __getitem__(self, idx):
        image, _ = self.dataset[idx]
        with torch.no_grad():
            x = image.unsqueeze(0).to(Config.DEVICE)
            y = self.physics(x).squeeze(0).cpu()
        return y, image

# ==========================================
# 4. HOAG UTILS
# ==========================================
def hessian_vector_product(inner_loss_fn, w_star, theta, y, physics_op, v):
    v_detached = v.detach()
    with torch.no_grad():
        Av = physics_op.A(v_detached)
        AtAv = physics_op.A_adjoint(Av)
    n = y.numel()
    term1 = (2.0 / n) * AtAv

    w_for_reg = w_star.detach().requires_grad_(True)
    with torch.enable_grad():
        reg = regularizer_only(w_for_reg, theta.detach())
        grad_reg = autograd.grad(reg, w_for_reg, create_graph=True)[0]
        grad_dot_v = torch.sum(grad_reg * v_detached)
        term2 = autograd.grad(grad_dot_v, w_for_reg, retain_graph=False)[0]

    return (term1 + term2.detach()).detach()

def conjugate_gradient(inner_loss_fn, w_star, theta, y, physics_op, b, max_iter=50, tol=1e-4, warm_start=None):
    b_norm = b.detach().norm().item()
    scaled_tol = tol * b_norm

    x = warm_start.detach().clone() if warm_start is not None else torch.zeros_like(b)

    if warm_start is not None:
        Ax = hessian_vector_product(inner_loss_fn, w_star, theta, y, physics_op, x) + 1e-3 * x
        r = b.detach() - Ax
    else:
        r = b.detach().clone()

    p = r.clone()
    rsold = torch.sum(r * r)

    for i in range(max_iter):
        if torch.sqrt(rsold) < scaled_tol: break
        Ap = hessian_vector_product(inner_loss_fn, w_star, theta, y, physics_op, p) + 1e-3 * p
        pAp = torch.sum(p * Ap)
        if pAp.abs() < 1e-12: break

        alpha = rsold / (pAp + 1e-8)
        x = x + alpha * p
        r = r - alpha * Ap
        rsnew = torch.sum(r * r)
        p = r + (rsnew / (rsold + 1e-8)) * p
        rsold = rsnew

    return x.detach()

# ==========================================
# 5. HOAG CORE
# ==========================================
class HOAGState:
    def __init__(self, init_tol, dec_type, dec_factor):
        self.epsilon_tol = init_tol
        self.dec_type = dec_type
        self.dec_factor = dec_factor
        self.q_warmstart = None

    def decrease_tolerance(self):
        if self.dec_type == 'exponential': self.epsilon_tol *= self.dec_factor
        self.epsilon_tol = max(self.epsilon_tol, 1e-12)

def solve_inner_problem(w_init, theta, y, physics_op, inner_loss_fn, state, lr, max_steps):
    w = w_init.detach().clone().requires_grad_(True)
    optimizer = torch.optim.Adam([w], lr=lr)

    # ADDED: Cosine Annealing to ensure smooth pixel convergence
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=max_steps, eta_min=lr * 0.01)

    with torch.enable_grad():
        loss_init = inner_loss_fn(w, theta.detach(), y, physics_op)
        grad_init = autograd.grad(loss_init, w)[0]
        norm_init = max(grad_init.norm().item(), 1e-12)

    stop_threshold = state.epsilon_tol * norm_init

    for step in range(max_steps):
        optimizer.zero_grad()
        loss = inner_loss_fn(w, theta.detach(), y, physics_op)
        loss.backward()
        if w.grad.norm().item() < stop_threshold: break
        optimizer.step()
        scheduler.step() # Step the scheduler

    return w

def hoag_step(theta, y, img_true, physics_op, inner_loss_fn, state, inner_lr, inner_steps, cg_max_iter):
    w_init = physics_op.A_dagger(y).detach().clone().clamp(0, 1)
    w_star = solve_inner_problem(w_init, theta, y, physics_op, inner_loss_fn, state, inner_lr, inner_steps)

    w_star = w_star.detach().requires_grad_(True)

    # UPPER LEVEL LOSS: Mean Squared Error
    val_loss = F.mse_loss(w_star.clamp(0, 1), img_true)

    # Compute Gradient of Upper Level Loss w.r.t w_star
    val_loss_grad_w = autograd.grad(val_loss, w_star, retain_graph=True)[0]

    q = conjugate_gradient(inner_loss_fn, w_star, theta, y, physics_op, b=val_loss_grad_w,
                           max_iter=cg_max_iter, tol=state.epsilon_tol, warm_start=state.q_warmstart)
    state.q_warmstart = q.detach().clone()

    w_cross = w_star.detach().requires_grad_(True)
    th_cross = theta.detach().requires_grad_(True)

    with torch.enable_grad():
        loss_cross = inner_loss_fn(w_cross, th_cross, y, physics_op)
        grad_w_cross = autograd.grad(loss_cross, w_cross, create_graph=True)[0]
        grad_dot_q = torch.sum(grad_w_cross * q.detach())
        cross_grad_theta = autograd.grad(grad_dot_q, th_cross)[0]

    return -cross_grad_theta.detach(), val_loss.item(), w_star

# ==========================================
# 6. MAIN EXECUTION
# ==========================================
print("Setting up Deterministic HOAG Environment (23x23 Physics Kernel)...")
physics = Physics2D(Config.BLUR_SIGMA, Config.NOISE_SIGMA, Config.DEVICE)

train_ds = BlurMNISTDataset(physics, train=True, subset_size=Config.SUBSET_SIZE)
train_loader = DataLoader(train_ds, batch_size=Config.SUBSET_SIZE, shuffle=False)
y_all, img_true_all = next(iter(train_loader))

y_all = y_all.to(Config.DEVICE)
img_true_all = img_true_all.to(Config.DEVICE)

# Initialize theta
theta = torch.tensor([-1.0, -4.0], device=Config.DEVICE).requires_grad_(True)
opt_theta = torch.optim.Adam([theta], lr=Config.LR_THETA)

hoag_state = HOAGState(Config.HOAG_EPSILON_TOL_INIT, Config.HOAG_TOLERANCE_DECREASE, Config.HOAG_DECREASE_FACTOR)

print(f"\nStarting Bilevel Optimization for Image Reconstruction (N={Config.SUBSET_SIZE} Images)...\n")
start_time = time.time()
w_star = None

for ep in range(Config.EPOCHS):
    epoch_start = time.time()

    hyper_grad, val_loss_val, w_star = hoag_step(
        theta, y_all, img_true_all, physics, inner_loss_func,
        hoag_state, Config.INNER_LR, Config.INNER_STEPS, Config.HOAG_CG_MAX_ITER
    )

    opt_theta.zero_grad()
    theta.grad = hyper_grad
    torch.nn.utils.clip_grad_norm_([theta], max_norm=1.0)
    opt_theta.step()

    reg_val, smooth_val = torch.exp(theta[0]).item(), torch.exp(theta[1]).item()
    sys.stdout.write(f"\rEpoch [{ep+1}/{Config.EPOCHS}] | "
                     f"Val MSE Loss: {val_loss_val:.4f} | Reg Weight: {reg_val:.4f} | Smooth: {smooth_val:.4f}")
    sys.stdout.flush()

    hoag_state.decrease_tolerance()
    epoch_time = (time.time() - epoch_start) / 60
    print(f"\n  -> Epoch {ep+1} Complete ({epoch_time:.1f} mins). HOAG Tol: {hoag_state.epsilon_tol:.2e}\n")

total_time = (time.time() - start_time) / 60
print(f"FULL HOAG Training Complete in {total_time:.2f} minutes!")

# ==========================================
# 7. VISUALIZE RESULTS
# ==========================================
def visualize_results(y, img_true, w_star, num_images=5):
    print(f"\nGenerating visualization for {num_images} sample images...")

    y = y.cpu().detach()
    img_true = img_true.cpu().detach()
    w_star = w_star.cpu().detach()

    num_images = min(num_images, y.shape[0])
    fig, axes = plt.subplots(num_images, 3, figsize=(10, 3 * num_images))

    if num_images == 1:
        axes = [axes]

    for i in range(num_images):
        axes[i][0].imshow(img_true[i].squeeze(), cmap='gray')
        axes[i][0].set_title("Ground Truth")
        axes[i][0].axis('off')

        axes[i][1].imshow(y[i].squeeze(), cmap='gray')
        axes[i][1].set_title("Measurement (Blur + Noise)")
        axes[i][1].axis('off')

        axes[i][2].imshow(w_star[i].squeeze(), cmap='gray', vmin=0, vmax=1)
        axes[i][2].set_title("HOAG Reconstruction")
        axes[i][2].axis('off')

    plt.tight_layout()
    plt.show()

if w_star is not None:
    visualize_results(y_all, img_true_all, w_star, num_images=5)

import numpy as np

rng = np.random.default_rng(0)

N, H, W = 2, 8, 8          # 2 images, 8x8  (full-batch tensor [N,H,W])
KS, SIG = 5, 1.0
MU = 1e-2                   # ridge -> strict strong convexity for the check


def gaussian_kernel(ks, sig):
    ax = np.arange(ks) - (ks - 1) / 2.0
    xx, yy = np.meshgrid(ax, ax, indexing="ij")
    k = np.exp(-(xx**2 + yy**2) / (2 * sig**2))
    return k / k.sum()

K = gaussian_kernel(KS, SIG)
P = KS // 2

# ---- A via spatial circular correlation (matches torch circular-pad conv2d) ----
def A_spatial(x):
    out = np.zeros_like(x)
    for a in range(KS):
        for b in range(KS):
            sa, sb = a - P, b - P
            out += K[a, b] * np.roll(x, shift=(-sa, -sb), axis=(-2, -1))
    return out

# ---- A via FFT OTF (matches the script's A_dagger construction) ----
def build_otf():
    psf = np.zeros((H, W))
    psf[:KS, :KS] = K
    psf = np.roll(psf, shift=(-(KS // 2), -(KS // 2)), axis=(0, 1))
    return np.fft.fft2(psf)

OTF = build_otf()
def A_fft(x):
    return np.real(np.fft.ifft2(OTF[None] * np.fft.fft2(x)))

# (1) self-adjointness
u, v = rng.standard_normal((N, H, W)), rng.standard_normal((N, H, W))
lhs, rhs = np.sum(A_spatial(u) * v), np.sum(u * A_spatial(v))
print(f"(1) self-adjoint  <Au,v>={lhs:.6f}  <u,Av>={rhs:.6f}  "
      f"rel.diff={abs(lhs-rhs)/abs(lhs):.2e}")

# (2) spatial vs FFT operator
d = np.abs(A_spatial(u) - A_fft(u)).max()
print(f"(2) spatial vs FFT operator  max|diff|={d:.2e}")

A = A_spatial  # use the spatial (conv-equivalent) operator from here on

# ---------------- data ----------------
x_clean = np.clip(rng.uniform(0, 1, (N, H, W)), 0, 1)
y = A(x_clean) + 0.01 * rng.standard_normal((N, H, W))

# ---------------- smoothed-TV Phi, analytic grad / HVP / cross ----------------
def tv_terms(x):
    dh = np.roll(x, -1, axis=-2) - x
    dv = np.roll(x, -1, axis=-1) - x
    return dh, dv

def Phi(x, theta):
    lam, eps = np.exp(theta[0]), np.exp(theta[1])
    dh, dv = tv_terms(x)
    tv = np.sqrt(dh**2 + dv**2 + eps).sum()
    return 0.5*np.sum((y - A(x))**2) + lam*tv + 0.5*MU*np.sum(x**2)

def grad_x(x, theta):
    lam, eps = np.exp(theta[0]), np.exp(theta[1])
    dh, dv = tv_terms(x)
    w = 1.0/np.sqrt(dh**2 + dv**2 + eps)
    a, c = dh*w, dv*w
    # adjoints of forward-difference operators: D^T z = roll(z,+1) - z
    dtv = (np.roll(a, 1, axis=-2) - a) + (np.roll(c, 1, axis=-1) - c)
    return A(A(x) - y) + lam*dtv + MU*x      # A self-adjoint -> A^T = A

def hvp(x, theta, vvec, h=1e-5):            # numerical Hessian-vector product
    return (grad_x(x + h*vvec, theta) - grad_x(x - h*vvec, theta)) / (2*h)

def cg(matvec, b, iters=400, tol=1e-12):
    q = np.zeros_like(b); r = b.copy(); p = r.copy(); rs = np.sum(r*r)
    for _ in range(iters):
        if np.sqrt(rs) < tol: break
        Hp = matvec(p); alpha = rs/np.sum(p*Hp)
        q += alpha*p; r -= alpha*Hp; rs_new = np.sum(r*r)
        p = r + (rs_new/rs)*p; rs = rs_new
    return q

def solve_inner(theta, newton_steps=12):     # accurate x*(theta) via Newton-CG
    x = y.copy()
    for _ in range(newton_steps):
        g = grad_x(x, theta)
        delta = cg(lambda vv: hvp(x, theta, vv), g)
        x = x - delta
    return x

def upper(x):  return np.mean((x - x_clean)**2)
def J(theta):  return upper(solve_inner(theta))

# ---------------- HOAG hypergradient (same steps as the Torch script) --------
def hoag_hypergrad(theta):
    xs = solve_inner(theta)
    b = (2.0/x_clean.size)*(xs - x_clean)            # grad_x upper
    q = cg(lambda vv: hvp(xs, theta, vv), b)          # H^{-1} b
    # hyper = - d/dtheta ( grad_x(xs,theta)^T q ), q held fixed
    eps_fd = 1e-5; g = np.zeros(2)
    for j in range(2):
        tp, tm = theta.copy(), theta.copy()
        tp[j] += eps_fd; tm[j] -= eps_fd
        sp = np.sum(grad_x(xs, tp)*q); sm = np.sum(grad_x(xs, tm)*q)
        g[j] = -(sp - sm)/(2*eps_fd)
    return g

theta0 = np.array([np.log(5e-3), np.log(1e-2)])
hg = hoag_hypergrad(theta0)

# finite-difference of the TRUE outer loss J(theta)
fd = np.zeros(2); e = 1e-4
for j in range(2):
    tp, tm = theta0.copy(), theta0.copy()
    tp[j] += e; tm[j] -= e
    fd[j] = (J(tp) - J(tm))/(2*e)

print("\n(3) HOAG hypergradient check at theta =", theta0)
print(f"    HOAG  : {hg}")
print(f"    FD(J) : {fd}")
rel = np.linalg.norm(hg - fd)/ (np.linalg.norm(fd)+1e-12)
print(f"    relative error = {rel:.3e}  -> {'PASS' if rel < 1e-2 else 'FAIL'}")

# ============================================================================
#  Bilevel Image Reconstruction on MNIST via HOAG
# ============================================================================

import math
import random

import numpy as np
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

import torchvision
from torchvision import transforms


# ============================================================================
# CONFIGURATION
# ============================================================================
class Cfg:
    SEED          = 0          # master seed -> full determinism

    # --- data ---
    N_IMAGES      = 100        # exactly 100 MNIST images (full batch)
    IMG_SIZE      = 28

    # --- corruption (SPCOM "Classification of blurry and noisy images") ---
    BLUR_KSIZE    = 23         # 23 x 23 Gaussian blur kernel
    BLUR_SIGMA    = 3.0        # std of the blur kernel (severe blur)
    NOISE_SIGMA   = 0.01       # additive Gaussian measurement noise sigma_w
    WIENER_ALPHA  = 1e-2       # Tikhonov constant for the A^dagger init only

    # --- inner (lower-level) solver: Adam on the pixels ---
    INNER_STEPS   = 300        # max Adam iterations N_it
    INNER_LR      = 0.05       # inner learning rate

    # --- HOAG hypergradient (CG to invert the inner Hessian) ---
    CG_MAX_ITER   = 30
    CG_DAMPING    = 1e-3       # ridge ~ strong-convexity floor mu(theta)

    # --- outer (upper-level) optimization over theta = (lambda, eps) ---
    OUTER_STEPS   = 40         # HOAG outer iterations
    OUTER_LR      = 0.10       # Adam learning rate for theta
    EPS_TOL_INIT  = 1e-1       # initial inner/CG tolerance epsilon_0
    EPS_DECAY     = 0.88       # exponential decrease of the tolerance schedule

    # --- TV hyperparameter initialization (stored as logs -> positivity) ---
    LOG_LAMBDA0   = math.log(5e-3)   # initial regularization weight lambda
    LOG_EPS0      = math.log(1e-2)   # initial TV smoothing parameter eps

    N_SHOW        = 8          # how many digits to show in the comparison plot
    DEVICE        = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ============================================================================
#  1.  DETERMINISM
# ============================================================================
def set_all_seeds(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    # Best-effort fully deterministic kernels (warn-only so Colab never crashes).
    try:
        torch.use_deterministic_algorithms(True, warn_only=True)
    except Exception:
        pass


set_all_seeds(Cfg.SEED)
print(f"Device: {Cfg.DEVICE}")


# ============================================================================
#  2.  DATA  -- exactly 100 MNIST images as ONE full-batch tensor
# ============================================================================
def load_mnist_fullbatch(n_images: int, device) -> torch.Tensor:
    """Download MNIST and return the first `n_images` as a single
    [n_images, 1, 28, 28] tensor in [0, 1].  The first-N selection is fixed,
    so the dataset is identical on every run (deterministic, no shuffling)."""
    ds = torchvision.datasets.MNIST(
        root="./data", train=True, download=True, transform=transforms.ToTensor()
    )
    imgs = torch.stack([ds[i][0] for i in range(n_images)], dim=0)  # [N,1,28,28]
    return imgs.to(device)


x_clean = load_mnist_fullbatch(Cfg.N_IMAGES, Cfg.DEVICE)   # ground truth, [0,1]
print(f"Clean image batch: {tuple(x_clean.shape)}  range=[{x_clean.min():.2f}, {x_clean.max():.2f}]")


# ============================================================================
#  3.  FORWARD OPERATOR A
# ============================================================================
def gaussian_kernel(ksize: int, sigma: float, device) -> torch.Tensor:
    ax = torch.arange(ksize, dtype=torch.float32, device=device) - (ksize - 1) / 2.0
    xx, yy = torch.meshgrid(ax, ax, indexing="ij")
    k = torch.exp(-(xx ** 2 + yy ** 2) / (2.0 * sigma ** 2))
    k = k / k.sum()                      # normalize -> preserves image mean
    return k                             # [ksize, ksize]


_KERNEL = gaussian_kernel(Cfg.BLUR_KSIZE, Cfg.BLUR_SIGMA, Cfg.DEVICE)
_KERNEL4 = _KERNEL.view(1, 1, Cfg.BLUR_KSIZE, Cfg.BLUR_KSIZE)
_PAD = Cfg.BLUR_KSIZE // 2


def A(x: torch.Tensor) -> torch.Tensor:
    """Apply the Gaussian-blur forward operator (circular padding)."""
    xp = F.pad(x, (_PAD, _PAD, _PAD, _PAD), mode="circular")
    return F.conv2d(xp, _KERNEL4)        # symmetric kernel -> A is self-adjoint


# --- Optical transfer function (OTF) for the FFT-based pseudo-inverse init ---
def _build_otf(kernel2d: torch.Tensor, shape, device) -> torch.Tensor:
    """psf2otf: place the kernel with its center at the (0,0) origin (parity-
    robust) so that the FFT operator exactly matches the circular conv A."""
    H, W = shape
    k = kernel2d.shape[0]
    psf = torch.zeros(H, W, device=device)
    psf[:k, :k] = kernel2d                      # kernel center sits at (k//2, k//2)
    psf = torch.roll(psf, shifts=(-(k // 2), -(k // 2)), dims=(0, 1))  # -> (0,0)
    return torch.fft.fft2(psf)                  # OTF, consistent with circular A


_OTF = _build_otf(_KERNEL, (Cfg.IMG_SIZE, Cfg.IMG_SIZE), Cfg.DEVICE)


@torch.no_grad()
def A_dagger(y: torch.Tensor, alpha: float = Cfg.WIENER_ALPHA) -> torch.Tensor:
    """Tikhonov-regularized pseudo-inverse  A^dagger y  =  IFFT( conj(K) Y /
    (|K|^2 + alpha) ).  Used only to warm-start the inner solver."""
    Y = torch.fft.fft2(y)
    X = (torch.conj(_OTF) / (_OTF.abs() ** 2 + alpha)) * Y
    return torch.fft.ifft2(X).real


# ============================================================================
#  4.  CORRUPTED IMAGING
# ============================================================================
def make_measurements(x_clean: torch.Tensor) -> torch.Tensor:
    gen = torch.Generator(device="cpu").manual_seed(Cfg.SEED + 1)   # fixed noise
    noise = torch.randn(x_clean.shape, generator=gen).to(x_clean.device)
    return A(x_clean) + Cfg.NOISE_SIGMA * noise


y = make_measurements(x_clean)                          # measurements, [100,1,28,28]
print(f"Measurement batch:  {tuple(y.shape)}")


# ============================================================================
#  5.  REGULARIZER  g_theta  +  LOWER-LEVEL OBJECTIVE  Phi
# ============================================================================
def tv_regularizer(x: torch.Tensor, theta: torch.Tensor) -> torch.Tensor:
    lam = torch.exp(theta[0])
    eps = torch.exp(theta[1])
    dh = torch.roll(x, shifts=-1, dims=2) - x          # vertical differences
    dv = torch.roll(x, shifts=-1, dims=3) - x          # horizontal differences
    tv = torch.sqrt(dh ** 2 + dv ** 2 + eps)
    return lam * tv.sum()


def Phi(x: torch.Tensor, theta: torch.Tensor) -> torch.Tensor:
    """Lower-level objective: 1/2 ||y - A x||^2 + g_theta(x), summed over the
    full batch (separable across images -> joint minimizer == per-image)."""
    data_fidelity = 0.5 * ((y - A(x)) ** 2).sum()
    return data_fidelity + tv_regularizer(x, theta)


def upper_loss(x: torch.Tensor) -> torch.Tensor:
    """Upper-level objective: mean-squared error against the clean images."""
    return ((x - x_clean) ** 2).mean()


# ============================================================================
#  6.  INNER SOLVER
# ============================================================================
def solve_inner(theta: torch.Tensor, eps_tol: float):
    """Approximate x*(theta) = argmin_x Phi(x, theta).
    Stops when the gradient norm drops below (eps_tol * initial gradient norm)
    or after INNER_STEPS iterations -- the HOAG inner-accuracy criterion."""
    x = A_dagger(y).clamp(0.0, 1.0).detach().clone().requires_grad_(True)  # x0 = A^dagger y

    opt = torch.optim.Adam([x], lr=Cfg.INNER_LR)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(
        opt, T_max=Cfg.INNER_STEPS, eta_min=Cfg.INNER_LR * 0.01)

    # reference gradient norm at the starting point (for a relative tolerance)
    g0 = torch.autograd.grad(Phi(x, theta.detach()), x)[0].norm().item()
    g0 = max(g0, 1e-12)
    stop = eps_tol * g0

    last_gnorm = g0
    for _ in range(Cfg.INNER_STEPS):
        opt.zero_grad()
        loss = Phi(x, theta.detach())
        loss.backward()
        last_gnorm = x.grad.norm().item()
        opt.step()
        sched.step()
        if last_gnorm < stop:
            break
    return x.detach(), last_gnorm


# ============================================================================
#  7.  HESSIAN-VECTOR PRODUCT  +  CONJUGATE GRADIENT
# ============================================================================
def make_hvp(x_star: torch.Tensor, theta: torch.Tensor):
    """Return a closure v -> H v evaluated at (x_star, theta); the graph for the
    inner gradient is built once and reused across CG iterations."""
    x = x_star.detach().clone().requires_grad_(True)
    grad_x = torch.autograd.grad(Phi(x, theta.detach()), x, create_graph=True)[0]

    def hvp(v: torch.Tensor) -> torch.Tensor:
        Hv = torch.autograd.grad(grad_x, x, grad_outputs=v.detach(),
                                 retain_graph=True)[0]
        return Hv + Cfg.CG_DAMPING * v        # small ridge for CG stability
    return hvp


def conjugate_gradient(hvp, b: torch.Tensor, max_iter: int, tol: float,
                       warm_start=None):
    """Solve H q = b for q using Conjugate Gradient (matrix-free)."""
    if warm_start is not None and warm_start.shape == b.shape:
        q = warm_start.detach().clone()
        r = b - hvp(q)
    else:
        q = torch.zeros_like(b)
        r = b.clone()
    p = r.clone()
    rs_old = (r * r).sum()
    b_norm = b.norm().item()
    thresh = tol * b_norm

    for _ in range(max_iter):
        if math.sqrt(rs_old.item()) < thresh:
            break
        Hp = hvp(p)
        pHp = (p * Hp).sum()
        if pHp.abs().item() < 1e-16:
            break
        alpha = rs_old / pHp
        q = q + alpha * p
        r = r - alpha * Hp
        rs_new = (r * r).sum()
        p = r + (rs_new / rs_old) * p
        rs_old = rs_new
    return q.detach()


# ============================================================================
#  8.  HOAG HYPERGRADIENT COMPUTATION
# ============================================================================
def hoag_hypergradient(theta, eps_tol, q_warm=None):
    # (1) inner solve to tolerance eps_tol
    x_star, inner_gnorm = solve_inner(theta, eps_tol)

    # (2) gradient of the UPPER objective w.r.t. the reconstruction
    xb = x_star.detach().clone().requires_grad_(True)
    J = upper_loss(xb)
    b = torch.autograd.grad(J, xb)[0]

    # (3) invert the inner Hessian against b with CG  ->  q = H^{-1} b
    hvp = make_hvp(x_star, theta)
    q = conjugate_gradient(hvp, b, Cfg.CG_MAX_ITER, eps_tol, warm_start=q_warm)

    # (4) mixed-partial contraction  ->  approximate hypergradient
    xc = x_star.detach().clone().requires_grad_(True)
    tc = theta.detach().clone().requires_grad_(True)
    grad_x = torch.autograd.grad(Phi(xc, tc), xc, create_graph=True)[0]
    cross = torch.autograd.grad((grad_x * q.detach()).sum(), tc)[0]
    hyper_grad = -cross

    return hyper_grad.detach(), J.item(), x_star, q, inner_gnorm


# ============================================================================
#  9.  OUTER OPTIMIZATION LOOP
# ============================================================================
def run_hoag():
    theta = torch.tensor([Cfg.LOG_LAMBDA0, Cfg.LOG_EPS0],
                         device=Cfg.DEVICE, requires_grad=True)
    opt = torch.optim.Adam([theta], lr=Cfg.OUTER_LR)

    eps_tol = Cfg.EPS_TOL_INIT
    q_warm = None
    history = {"mse": [], "lambda": [], "eps": [], "tol": []}
    x_star = None

    print("\n" + "=" * 74)
    print(f"{'iter':>4} | {'outer MSE':>11} | {'lambda':>10} | {'eps':>10} | "
          f"{'tol':>8} | {'||g_in||':>9}")
    print("=" * 74)

    for it in range(Cfg.OUTER_STEPS):
        hyper_grad, mse, x_star, q, inner_gnorm = hoag_hypergradient(
            theta, eps_tol, q_warm)
        q_warm = q                              # warm-start next CG solve

        opt.zero_grad()
        theta.grad = hyper_grad                 # inject the HOAG hypergradient
        opt.step()

        lam = math.exp(theta[0].item())
        eps = math.exp(theta[1].item())
        history["mse"].append(mse)
        history["lambda"].append(lam)
        history["eps"].append(eps)
        history["tol"].append(eps_tol)

        if it % 2 == 0 or it == Cfg.OUTER_STEPS - 1:
            print(f"{it:>4} | {mse:>11.6f} | {lam:>10.5f} | {eps:>10.5f} | "
                  f"{eps_tol:>8.1e} | {inner_gnorm:>9.2e}")

        eps_tol = max(eps_tol * Cfg.EPS_DECAY, 1e-10)   # tighten tolerance

    # final reconstruction at the learned theta, solved tightly
    x_final, _ = solve_inner(theta.detach(), eps_tol=1e-6)
    return theta.detach(), x_final, history


theta_star, x_recon, hist = run_hoag()


# ============================================================================
#  10.  METRICS
# ============================================================================
def psnr(a: torch.Tensor, b: torch.Tensor) -> float:
    mse = ((a.clamp(0, 1) - b.clamp(0, 1)) ** 2).mean().item()
    return 10.0 * math.log10(1.0 / max(mse, 1e-12))


mse_corrupt = ((y - x_clean) ** 2).mean().item()
mse_recon   = ((x_recon - x_clean) ** 2).mean().item()

print("\n" + "=" * 74)
print("RESULTS")
print("=" * 74)
print(f"Learned lambda           : {math.exp(theta_star[0].item()):.6f}")
print(f"Learned eps (TV smooth)  : {math.exp(theta_star[1].item()):.6f}")
print(f"MSE   corrupted vs clean : {mse_corrupt:.6f}   (PSNR {psnr(y, x_clean):.2f} dB)")
print(f"MSE   reconstr vs clean  : {mse_recon:.6f}   (PSNR {psnr(x_recon, x_clean):.2f} dB)")
print(f"MSE reduction            : {100 * (1 - mse_recon / mse_corrupt):.1f}%")

# ============================================================================
#  11.  VISUALIZATION
# ============================================================================
def to_np(t):
    return t.detach().cpu().squeeze(1).clamp(0, 1).numpy()

xc_np, y_np, xr_np = to_np(x_clean), to_np(y), to_np(x_recon)
n = Cfg.N_SHOW

# ---- (a) side-by-side image comparison ----
fig, axes = plt.subplots(3, n, figsize=(1.5 * n, 5.0))
row_titles = ["Original", "Corrupted", "Reconstructed"]
rows = [xc_np, y_np, xr_np]
for r, (title, data) in enumerate(zip(row_titles, rows)):
    for c in range(n):
        ax = axes[r, c]
        ax.imshow(data[c], cmap="gray", vmin=0, vmax=1)
        ax.set_xticks([]); ax.set_yticks([])
        if c == 0:
            ax.set_ylabel(title, fontsize=11)
fig.suptitle("HOAG bilevel reconstruction on MNIST (smoothed-TV regularizer)",
             fontsize=13)
fig.tight_layout()
fig.savefig("hoag_mnist_comparison.png", dpi=140, bbox_inches="tight")
plt.show()

# ---- (b) outer-loss curve and the learned hyperparameters ----
fig2, ax = plt.subplots(1, 3, figsize=(13, 3.4))
ax[0].plot(hist["mse"], marker="o", ms=3)
ax[0].set_title("Outer objective (MSE vs clean)")
ax[0].set_xlabel("HOAG outer iteration"); ax[0].set_ylabel("MSE"); ax[0].grid(alpha=.3)

ax[1].plot(hist["lambda"], marker="o", ms=3, color="tab:orange")
ax[1].set_title(r"Learned regularization weight $\lambda$")
ax[1].set_xlabel("HOAG outer iteration"); ax[1].grid(alpha=.3)

ax[2].plot(hist["tol"], marker="o", ms=3, color="tab:green")
ax[2].set_title(r"Inner/CG tolerance schedule $\epsilon_k$")
ax[2].set_xlabel("HOAG outer iteration"); ax[2].set_yscale("log"); ax[2].grid(alpha=.3)

fig2.tight_layout()
fig2.savefig("hoag_mnist_diagnostics.png", dpi=140, bbox_inches="tight")
plt.show()

print("\nSaved figures: hoag_mnist_comparison.png , hoag_mnist_diagnostics.png")

# ============================================================================
#  Bilevel Image Reconstruction on MNIST via HOAG
# ============================================================================

import math
import random

import numpy as np
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

import torchvision
from torchvision import transforms


# ============================================================================
#  CONFIGURATION
# ============================================================================
class Cfg:

    SEED          = 0

    # --- data ---
    N_IMAGES      = 100
    IMG_SIZE      = 28


    BLUR_KSIZE    = 23
    BLUR_SIGMA    = 3.0
    NOISE_SIGMA   = 0.01
    WIENER_ALPHA  = 1e-2

    # --- Field-of-Experts regularizer (SPCOM Eq.4 / repo mnist_foe) ---
    NUM_EXPERTS   = 5          # L : number of learnable filters
    FILTER_SIZE   = 5          # K : filter is K x K size
    IN_CHANNELS   = 1          # grayscale
    CLAMP_MAX     = 2.0        # clamp on log-weights before exp (repo, stability)
    GLOBAL_W_INIT = -3.0       # theta0
    FILTER_W_INIT = -5.0       # beta_j
    SMOOTH_INIT   = -4.6       # s_j

    # --- inner (lower-level) solver: Adam on the pixels ---
    INNER_STEPS         = 300
    INNER_LR            = 0.05
    INNER_STEPS_FINAL   = 2000

    # --- HOAG hypergradient (CG to invert the inner Hessian) ---
    CG_MAX_ITER   = 30
    CG_DAMPING    = 1e-3

    # --- outer (upper-level) optimization over theta (136 numbers) ---
    OUTER_STEPS   = 40
    OUTER_LR      = 0.02
    EPS_TOL_INIT  = 1e-1
    EPS_DECAY     = 0.88

    N_SHOW        = 8
    DEVICE        = torch.device("cuda" if torch.cuda.is_available() else "cpu")


# ============================================================================
# DETERMINISM
# ============================================================================
def set_all_seeds(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    try:
        torch.use_deterministic_algorithms(True, warn_only=True)
    except Exception:
        pass


set_all_seeds(Cfg.SEED)
print(f"Device: {Cfg.DEVICE}")


# ============================================================================
# DATA  -- 100 MNIST images as one full-batch tensor
# ============================================================================
def load_mnist_fullbatch(n_images: int, device) -> torch.Tensor:
    ds = torchvision.datasets.MNIST(
        root="./data", train=True, download=True, transform=transforms.ToTensor()
    )
    imgs = torch.stack([ds[i][0] for i in range(n_images)], dim=0)
    return imgs.to(device)


x_clean = load_mnist_fullbatch(Cfg.N_IMAGES, Cfg.DEVICE)
print(f"Clean image batch: {tuple(x_clean.shape)}  range=[{x_clean.min():.2f}, {x_clean.max():.2f}]")


# ============================================================================
# FORWARD OPERATOR A
# ============================================================================
def gaussian_kernel(ksize: int, sigma: float, device) -> torch.Tensor:
    ax = torch.arange(ksize, dtype=torch.float32, device=device) - (ksize - 1) / 2.0
    xx, yy = torch.meshgrid(ax, ax, indexing="ij")
    k = torch.exp(-(xx ** 2 + yy ** 2) / (2.0 * sigma ** 2))
    return k / k.sum()


_KERNEL = gaussian_kernel(Cfg.BLUR_KSIZE, Cfg.BLUR_SIGMA, Cfg.DEVICE)
_KERNEL4 = _KERNEL.view(1, 1, Cfg.BLUR_KSIZE, Cfg.BLUR_KSIZE)
_PAD = Cfg.BLUR_KSIZE // 2


def A(x: torch.Tensor) -> torch.Tensor:
    xp = F.pad(x, (_PAD, _PAD, _PAD, _PAD), mode="circular")
    return F.conv2d(xp, _KERNEL4)        # symmetric kernel -> A is self-adjoint


def _build_otf(kernel2d: torch.Tensor, shape, device) -> torch.Tensor:
    H, W = shape
    k = kernel2d.shape[0]
    psf = torch.zeros(H, W, device=device)
    psf[:k, :k] = kernel2d
    psf = torch.roll(psf, shifts=(-(k // 2), -(k // 2)), dims=(0, 1))
    return torch.fft.fft2(psf)


_OTF = _build_otf(_KERNEL, (Cfg.IMG_SIZE, Cfg.IMG_SIZE), Cfg.DEVICE)


@torch.no_grad()
def A_dagger(y: torch.Tensor, alpha: float = Cfg.WIENER_ALPHA) -> torch.Tensor:
    Y = torch.fft.fft2(y)
    X = (torch.conj(_OTF) / (_OTF.abs() ** 2 + alpha)) * Y
    return torch.fft.ifft2(X).real


# ============================================================================
# y = A x_clean + Gaussian noise
# ============================================================================
def make_measurements(x_clean: torch.Tensor) -> torch.Tensor:
    gen = torch.Generator(device="cpu").manual_seed(Cfg.SEED + 1)
    noise = torch.randn(x_clean.shape, generator=gen).to(x_clean.device)
    return A(x_clean) + Cfg.NOISE_SIGMA * noise


y = make_measurements(x_clean)
print(f"Measurement batch:  {tuple(y.shape)}")


# ============================================================================
# FIELD-OF-EXPERTS REGULARIZER  +  LOWER-LEVEL OBJECTIVE
# ============================================================================
_L, _K, _C = Cfg.NUM_EXPERTS, Cfg.FILTER_SIZE, Cfg.IN_CHANNELS
THETA_SIZE = 1 + _L + _L + _L * _C * _K * _K # (K²+2)L+1 formula


def parse_theta(theta: torch.Tensor):
    """Split the flat hyperparameter vector into its named parts."""
    i = 0
    theta0 = theta[i];                       i += 1
    beta   = theta[i:i + _L];                i += _L
    s      = theta[i:i + _L];                i += _L
    filt   = theta[i:].view(_L, _C, _K, _K)
    return theta0, beta, s, filt


def initial_filter_bank(device) -> torch.Tensor:
    """Classical edge/blob detectors: horizontal, vertical, diagonal, anti-diagonal gradients + Laplacian-of-Gaussian."""
    filt = torch.zeros(_L, _C, _K, _K)
    h = torch.tensor([[-1, -1, 0, 1, 1],
                      [-2, -2, 0, 2, 2],
                      [-3, -3, 0, 3, 3],
                      [-2, -2, 0, 2, 2],
                      [-1, -1, 0, 1, 1]], dtype=torch.float32) / 12.0

    d = torch.tensor([[-2, -1, 0, 0, 0],
                      [-1, -2, 0, 0, 0],
                      [ 0,  0, 0, 0, 0],
                      [ 0,  0, 0, 2, 1],
                      [ 0,  0, 0, 1, 2]], dtype=torch.float32) / 6.0

    log = torch.tensor([[ 0,  0, -1,  0,  0],
                        [ 0, -1, -2, -1,  0],
                        [-1, -2, 16, -2, -1],
                        [ 0, -1, -2, -1,  0],
                        [ 0,  0, -1,  0,  0]], dtype=torch.float32) / 16.0

    for c in range(_C):
        filt[0, c] = h            # horizontal gradient
        filt[1, c] = h.T          # vertical gradient
        filt[2, c] = d            # diagonal
        filt[3, c] = d.flip(1)    # anti-diagonal
        filt[4, c] = log          # Laplacian-of-Gaussian
    return filt.to(device)


def initialize_theta(device) -> torch.Tensor:
    """Build the flat 136-vector of FoE hyperparameters (repo init values)."""
    theta0 = torch.tensor([Cfg.GLOBAL_W_INIT])
    beta   = torch.full((_L,), Cfg.FILTER_W_INIT)
    s      = torch.full((_L,), Cfg.SMOOTH_INIT)
    filt   = initial_filter_bank("cpu").flatten()
    return torch.cat([theta0, beta, s, filt]).to(device)


def foe_regularizer(x: torch.Tensor, theta: torch.Tensor) -> torch.Tensor:
    """g_theta(x) = e^{theta0} * sum_j e^{beta_j} * SUM_pix sqrt((c_j * x)^2 + nu_j^2).
    SUM form (see scaling note in the header). Filters use zero-padding (repo)."""
    theta0, beta, s, filt = parse_theta(theta)
    cm = Cfg.CLAMP_MAX
    pad = _K // 2
    total = x.new_zeros(())
    for j in range(_L):
        resp = F.conv2d(x, filt[j:j + 1], padding=pad)          # (c_j (*) x)
        nu_j = torch.exp(s[j].clamp(max=cm))                    # smoothing
        penalty = torch.sqrt(resp ** 2 + nu_j ** 2).sum()        # SUM_pix rho_nu(.)
        total = total + torch.exp(beta[j].clamp(max=cm)) * penalty
    return torch.exp(theta0.clamp(max=cm)) * total


def Phi(x: torch.Tensor, theta: torch.Tensor) -> torch.Tensor:
    """Lower-level objective  1/2 ||y - A x||^2 + g_theta(x), summed over the batch."""
    data_fidelity = 0.5 * ((y - A(x)) ** 2).sum()
    return data_fidelity + foe_regularizer(x, theta)


def upper_loss(x: torch.Tensor) -> torch.Tensor:
    """Upper-level objective: MSE against the clean images."""
    return ((x - x_clean) ** 2).mean()


# ============================================================================
# INNER SOLVER
# ============================================================================
def solve_inner(theta: torch.Tensor, eps_tol: float, max_steps=None, lr=None):
    max_steps = Cfg.INNER_STEPS if max_steps is None else max_steps
    lr = Cfg.INNER_LR if lr is None else lr

    x = A_dagger(y).clamp(0.0, 1.0).detach().clone().requires_grad_(True)  # x0 = A^dagger y
    opt = torch.optim.Adam([x], lr=lr)
    sched = torch.optim.lr_scheduler.CosineAnnealingLR(opt, T_max=max_steps, eta_min=lr * 0.01)

    g0 = torch.autograd.grad(Phi(x, theta.detach()), x)[0].norm().item()
    g0 = max(g0, 1e-12)
    stop = eps_tol * g0

    last_gnorm = g0
    for _ in range(max_steps):
        opt.zero_grad()
        loss = Phi(x, theta.detach())
        loss.backward()
        last_gnorm = x.grad.norm().item()
        opt.step()
        sched.step()
        if last_gnorm < stop:
            break
    return x.detach(), last_gnorm


# ============================================================================
# HESSIAN-VECTOR PRODUCT  +  CONJUGATE GRADIENT
# ============================================================================
def make_hvp(x_star: torch.Tensor, theta: torch.Tensor):
    x = x_star.detach().clone().requires_grad_(True)
    grad_x = torch.autograd.grad(Phi(x, theta.detach()), x, create_graph=True)[0]

    def hvp(v: torch.Tensor) -> torch.Tensor:
        Hv = torch.autograd.grad(grad_x, x, grad_outputs=v.detach(), retain_graph=True)[0]
        return Hv + Cfg.CG_DAMPING * v
    return hvp


def conjugate_gradient(hvp, b, max_iter, tol, warm_start=None):
    if warm_start is not None and warm_start.shape == b.shape:
        q = warm_start.detach().clone()
        r = b - hvp(q)
    else:
        q = torch.zeros_like(b)
        r = b.clone()
    p = r.clone()
    rs_old = (r * r).sum()
    thresh = tol * b.norm().item()
    for _ in range(max_iter):
        if math.sqrt(rs_old.item()) < thresh:
            break
        Hp = hvp(p)
        pHp = (p * Hp).sum()
        if pHp.abs().item() < 1e-16:
            break
        alpha = rs_old / pHp
        q = q + alpha * p
        r = r - alpha * Hp
        rs_new = (r * r).sum()
        p = r + (rs_new / rs_old) * p
        rs_old = rs_new
    return q.detach()


# ============================================================================
# HOAG HYPERGRADIENT  (Algorithm 2; b = grad of the MSE)
# ============================================================================
def hoag_hypergradient(theta, eps_tol, q_warm=None):
    x_star, inner_gnorm = solve_inner(theta, eps_tol)

    xb = x_star.detach().clone().requires_grad_(True)
    J = upper_loss(xb)
    b = torch.autograd.grad(J, xb)[0]                       # b = grad_x MSE

    hvp = make_hvp(x_star, theta)
    q = conjugate_gradient(hvp, b, Cfg.CG_MAX_ITER, eps_tol, warm_start=q_warm)

    xc = x_star.detach().clone().requires_grad_(True)
    tc = theta.detach().clone().requires_grad_(True)
    grad_x = torch.autograd.grad(Phi(xc, tc), xc, create_graph=True)[0]
    cross = torch.autograd.grad((grad_x * q.detach()).sum(), tc)[0]   # (d^2Phi/dxdtheta)^T q
    hyper_grad = -cross

    return hyper_grad.detach(), J.item(), x_star, q, inner_gnorm


# ============================================================================
# OUTER OPTIMIZATION LOOP
# ============================================================================
def run_hoag():
    theta = initialize_theta(Cfg.DEVICE).requires_grad_(True)
    opt = torch.optim.Adam([theta], lr=Cfg.OUTER_LR)

    init_filters = parse_theta(theta)[3].detach().clone()
    eps_tol = Cfg.EPS_TOL_INIT
    q_warm = None
    history = {"mse": [], "global_w": [], "mean_beta": [], "tol": []}

    print("\n" + "=" * 78)
    print(f"{'iter':>4} | {'outer MSE':>11} | {'e^theta0':>10} | {'mean e^beta':>11} | "
          f"{'tol':>8} | {'||g_in||':>9}")
    print("=" * 78)

    for it in range(Cfg.OUTER_STEPS):
        hyper_grad, mse, x_star, q, inner_gnorm = hoag_hypergradient(theta, eps_tol, q_warm)
        q_warm = q

        opt.zero_grad()
        theta.grad = hyper_grad
        opt.step()

        th0, beta, s, _ = parse_theta(theta)
        gw = math.exp(th0.item())
        mb = torch.exp(beta).mean().item()
        history["mse"].append(mse)
        history["global_w"].append(gw)
        history["mean_beta"].append(mb)
        history["tol"].append(eps_tol)

        if it % 2 == 0 or it == Cfg.OUTER_STEPS - 1:
            print(f"{it:>4} | {mse:>11.6f} | {gw:>10.4f} | {mb:>11.5f} | "
                  f"{eps_tol:>8.1e} | {inner_gnorm:>9.2e}")

        eps_tol = max(eps_tol * Cfg.EPS_DECAY, 1e-10)

    # final, high-accuracy reconstruction at the learned regularizer
    x_final, _ = solve_inner(theta.detach(), eps_tol=1e-6, max_steps=Cfg.INNER_STEPS_FINAL)
    learned_filters = parse_theta(theta)[3].detach().clone()
    return theta.detach(), x_final, history, init_filters, learned_filters


theta_star, x_recon, hist, init_filters, learned_filters = run_hoag()


# ============================================================================
# METRICS
# ============================================================================
def psnr(a: torch.Tensor, b: torch.Tensor) -> float:
    mse = ((a.clamp(0, 1) - b.clamp(0, 1)) ** 2).mean().item()
    return 10.0 * math.log10(1.0 / max(mse, 1e-12))


mse_corrupt = ((y - x_clean) ** 2).mean().item()
mse_recon   = ((x_recon - x_clean) ** 2).mean().item()
th0, beta, s, _ = parse_theta(theta_star)

print("\n" + "=" * 78)
print("RESULTS  (Field-of-Experts regularizer)")
print("=" * 78)
print(f"Learned global weight e^theta0 : {math.exp(th0.item()):.5f}")
print(f"Learned filter weights e^beta  : {[round(v,4) for v in torch.exp(beta).tolist()]}")
print(f"Learned smoothings    nu=e^s   : {[round(v,4) for v in torch.exp(s).tolist()]}")
print(f"MSE   corrupted vs clean       : {mse_corrupt:.6f}   (PSNR {psnr(y, x_clean):.2f} dB)")
print(f"MSE   reconstr vs clean        : {mse_recon:.6f}   (PSNR {psnr(x_recon, x_clean):.2f} dB)")
print(f"MSE reduction                  : {100 * (1 - mse_recon / mse_corrupt):.1f}%")

# ============================================================================
#  11.  VISUALIZATION
# ============================================================================
def to_np(t):
    return t.detach().cpu().squeeze(1).clamp(0, 1).numpy()

xc_np, y_np, xr_np = to_np(x_clean), to_np(y), to_np(x_recon)
n = Cfg.N_SHOW

# ---- (a) Original / Corrupted / Reconstructed ----
fig, axes = plt.subplots(3, n, figsize=(1.5 * n, 5.0))
for r, (title, data) in enumerate(zip(
        ["Original", "Measurement", "Reconstructed"],
        [xc_np, y_np, xr_np])):
    for c in range(n):
        ax = axes[r, c]
        ax.imshow(data[c], cmap="gray", vmin=0, vmax=1)
        ax.set_xticks([]); ax.set_yticks([])
        if c == 0:
            ax.set_ylabel(title, fontsize=11)
fig.suptitle("HOAG bilevel reconstruction on MNIST (Field-of-Experts regularizer)", fontsize=13)
fig.tight_layout()
fig.savefig("hoag_foe_comparison.png", dpi=140, bbox_inches="tight")
plt.show()

# ---- (b) outer loss, learned global weight, tolerance ----
fig2, ax = plt.subplots(1, 3, figsize=(13, 3.4))
ax[0].plot(hist["mse"], marker="o", ms=3)
ax[0].set_title("Outer objective (MSE vs clean)"); ax[0].set_xlabel("HOAG outer iteration")
ax[0].set_ylabel("MSE"); ax[0].grid(alpha=.3)
ax[1].plot(hist["global_w"], marker="o", ms=3, color="tab:orange")
ax[1].set_title(r"Learned global weight $e^{\theta_0}$"); ax[1].set_xlabel("HOAG outer iteration")
ax[1].grid(alpha=.3)
ax[2].plot(hist["tol"], marker="o", ms=3, color="tab:green")
ax[2].set_title(r"Inner/CG tolerance $\epsilon_k$"); ax[2].set_xlabel("HOAG outer iteration")
ax[2].set_yscale("log"); ax[2].grid(alpha=.3)
fig2.tight_layout()
fig2.savefig("hoag_foe_diagnostics.png", dpi=140, bbox_inches="tight")
plt.show()

# ---- (c) the FoE filters, before and after learning ----
fi = init_filters.detach().cpu().squeeze(1).numpy()
fl = learned_filters.detach().cpu().squeeze(1).numpy()
fig3, ax3 = plt.subplots(2, _L, figsize=(2.0 * _L, 4.2))
names = ["horiz", "vert", "diag", "anti-diag", "LoG"]
for j in range(_L):
    ax3[0, j].imshow(fi[j], cmap="gray"); ax3[0, j].set_xticks([]); ax3[0, j].set_yticks([])
    ax3[1, j].imshow(fl[j], cmap="gray"); ax3[1, j].set_xticks([]); ax3[1, j].set_yticks([])
    ax3[0, j].set_title(names[j] if j < len(names) else f"f{j}", fontsize=9)
ax3[0, 0].set_ylabel("initial", fontsize=11)
ax3[1, 0].set_ylabel("learned", fontsize=11)
fig3.suptitle("FoE filters: initial (edge/blob detectors) vs. HOAG-learned", fontsize=12)
fig3.tight_layout()
fig3.savefig("hoag_foe_filters.png", dpi=140, bbox_inches="tight")
plt.show()

print("\nSaved: hoag_foe_comparison.png , hoag_foe_diagnostics.png , hoag_foe_filters.png")