# -*- coding: utf-8 -*-
"""MNISTBilevel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VD1u8VkSnI5NXZ_L7QXLcRbotfEN5_9R
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/aryan18072003/bl_of_tar.git
# %cd bl_of_tar
!tree -L 2

!apt-get -qq install tree

!tree -L 2

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/bl_of_tar
!pip install -q monai deepinv torchvision torch torchaudio

!python task_adapted_recon_mnist/main.py

import torch

print(torch.cuda.is_available())

if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

!zip -r mnist_joint_results.zip /content/bl_of_tar/results

from PIL import Image
import matplotlib.pyplot as plt

img = Image.open('/content/bl_of_tar/results/joint/samples.png')

plt.figure(figsize=(12,6))
plt.imshow(img)
plt.axis('off')
plt.show()

!grep -R "mode =" -n /content/bl_of_tar/task_adapted_recon_mnist

!cat /content/bl_of_tar/task_adapted_recon_mnist/config.py

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/bl_of_tar

file_path = "task_adapted_recon_mnist/config.py"

with open(file_path, "r") as f:
    text = f.read()

text = text.replace(
    'mode: str = "joint"',
    'mode: str = "upper_bound"'
)

with open(file_path, "w") as f:
    f.write(text)

print("Config updated to upper_bound")

!python task_adapted_recon_mnist/main.py

!find /content/bl_of_tar/results/upper_bound -type f

!zip -r upper_bound_results.zip /content/bl_of_tar/results/upper_bound

from google.colab import files
files.download('upper_bound_results.zip')

from PIL import Image
import matplotlib.pyplot as plt

img = Image.open('/content/bl_of_tar/results/upper_bound/samples.png')

plt.figure(figsize=(15,8))
plt.imshow(img)
plt.axis('off')
plt.show()

mode: str = "sequential"

file_path = "/content/bl_of_tar/task_adapted_recon_mnist/config.py"

with open(file_path, "r") as f:
    text = f.read()

import re
text = re.sub(
    r'mode:\s*str\s*=\s*".*?"',
    'mode: str = "sequential"',
    text
)

with open(file_path, "w") as f:
    f.write(text)

print("Mode changed to sequential")

!grep "mode:" /content/bl_of_tar/task_adapted_recon_mnist/config.py

!python /content/bl_of_tar/task_adapted_recon_mnist/main.py

!find /content/bl_of_tar/results/sequential -type f

from PIL import Image
import matplotlib.pyplot as plt

img = Image.open('/content/bl_of_tar/results/sequential/samples.png')

plt.figure(figsize=(20,6))
plt.imshow(img)
plt.axis('off')
plt.show()

!zip -r mnist_results_so_far.zip /content/bl_of_tar/results

from google.colab import files
files.download('mnist_results_so_far.zip')

file_path = "/content/bl_of_tar/task_adapted_recon_mnist/config.py"

with open(file_path, "r") as f:
    text = f.read()

import re

text = re.sub(
    r'mode:\s*str\s*=\s*".*?"',
    'mode: str = "end_to_end"',
    text
)

with open(file_path, "w") as f:
    f.write(text)

print("Mode changed to end_to_end")

!grep "mode:" /content/bl_of_tar/task_adapted_recon_mnist/config.py

!python /content/bl_of_tar/task_adapted_recon_mnist/main.py

!find /content/bl_of_tar/results/end_to_end -type f

from google.colab import files
import os

folder = "/content/bl_of_tar/results/end_to_end"

for f in os.listdir(folder):
    if f.endswith(".pt"):
        print("Downloading:", f)
        files.download(os.path.join(folder, f))

from PIL import Image
import matplotlib.pyplot as plt

img = Image.open('/content/bl_of_tar/results/end_to_end/samples.png')

plt.figure(figsize=(18,6))
plt.imshow(img)
plt.axis('off')
plt.show()

!zip -r end_to_end_results.zip /content/bl_of_tar/results/end_to_end

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/bl_of_tar

!find . -iname "*bilevel*"
!find . -iname "*tv*"
!find . -iname "*foe*"
!find . -iname "*.py" | grep -E "tv|foe|bilevel|lower"

!sed -n '1,250p' /content/bl_of_tar/mnist_bilevel_learning/mnist_tv/main.py

!sed -n '1,250p' /content/bl_of_tar/mnist_bilevel_learning/mnist_foe/main.py

file_path = "/content/bl_of_tar/mnist_bilevel_learning/mnist_tv/main.py"

with open(file_path, "r") as f:
    text = f.read()

text = text.replace(
    'UPPER_BOUND_CKPT = "../../task_adapted_recon_mnist/results/upper_bound/upper_best.pt"',
    'UPPER_BOUND_CKPT = "/content/bl_of_tar/results/upper_bound/upper_best.pt"'
)

with open(file_path, "w") as f:
    f.write(text)

print("TV checkpoint path fixed")

!grep "UPPER_BOUND_CKPT" /content/bl_of_tar/mnist_bilevel_learning/mnist_tv/main.py

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/bl_of_tar/mnist_bilevel_learning/mnist_tv
!python main.py

!find /content/bl_of_tar/mnist_bilevel_learning/mnist_tv/results_mnist_tv -type f

!zip -r mnist_tv_results.zip \
/content/bl_of_tar/mnist_bilevel_learning/mnist_tv/results_mnist_tv

from PIL import Image
import matplotlib.pyplot as plt
import glob

files = glob.glob(
    "/content/bl_of_tar/mnist_bilevel_learning/mnist_tv/results_mnist_tv/*.png"
)

print(files)

for f in files:
    img = Image.open(f)

    plt.figure(figsize=(12,4))
    plt.imshow(img)
    plt.title(f.split("/")[-1])
    plt.axis("off")
    plt.show()

!find /content/bl_of_tar/mnist_bilevel_learning/mnist_tv/results_mnist_tv -type f

file_path = "/content/bl_of_tar/mnist_bilevel_learning/mnist_foe/main.py"

with open(file_path, "r") as f:
    text = f.read()

text = text.replace(
    "../../task_adapted_recon_mnist/results/upper_bound/upper_best.pt",
    "/content/bl_of_tar/results/upper_bound/upper_best.pt"
)

with open(file_path, "w") as f:
    f.write(text)

print("FoE checkpoint path patched")

!grep "UPPER_BOUND_CKPT" /content/bl_of_tar/mnist_bilevel_learning/mnist_foe/main.py

file_path = "/content/bl_of_tar/mnist_bilevel_learning/mnist_foe/main.py"

with open(file_path, "r") as f:
    text = f.read()

text = text.replace(
    "EPOCHS_HOAG = 15",
    "EPOCHS_HOAG = 0"
)

with open(file_path, "w") as f:
    f.write(text)

print("FoE HOAG disabled")

from google.colab import files
uploaded = files.upload()

!mkdir -p /content/bl_of_tar/results/upper_bound
!mv upper_best.pt /content/bl_of_tar/results/upper_bound/upper_best.pt

file_path = "/content/bl_of_tar/mnist_bilevel_learning/mnist_foe/main.py"

with open(file_path, "r") as f:
    text = f.read()

text = text.replace(
    "EPOCHS_HOAG = 15",
    "EPOCHS_HOAG = 0"
)

with open(file_path, "w") as f:
    f.write(text)

print("FoE config updated: EPOCHS_HOAG = 0")

!grep "EPOCHS_HOAG" /content/bl_of_tar/mnist_bilevel_learning/mnist_foe/main.py

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/bl_of_tar/mnist_bilevel_learning/mnist_foe
!python main.py

!find /content/bl_of_tar/mnist_bilevel_learning/mnist_foe/results_mnist_foe -type f

!zip -r mnist_foe_results.zip \
/content/bl_of_tar/mnist_bilevel_learning/mnist_foe/results_mnist_foe

!find /content/bl_of_tar -name "*.pt"

!find /content -name "upper_best.pt"

file_path = "/content/bl_of_tar/mnist_bilevel_learning/mnist_tv/main.py"

with open(file_path, "r") as f:
    text = f.read()

text = text.replace(
    "../../task_adapted_recon_mnist/results/upper_bound/upper_best.pt",
    "/content/bl_of_tar/results/upper_bound/upper_best.pt"
)

with open(file_path, "w") as f:
    f.write(text)

print("TV checkpoint path fixed.")

!grep "UPPER_BOUND_CKPT" /content/bl_of_tar/mnist_bilevel_learning/mnist_tv/main.py

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/bl_of_tar/mnist_bilevel_learning/mnist_tv
!python main.py

!find /content/bl_of_tar/mnist_bilevel_learning/mnist_tv/results_mnist_tv -type f

file_path = "/content/bl_of_tar/mnist_bilevel_learning/mnist_foe/main.py"

with open(file_path, "r") as f:
    text = f.read()

# Fix checkpoint path
text = text.replace(
    "../../task_adapted_recon_mnist/results/upper_bound/upper_best.pt",
    "/content/bl_of_tar/results/upper_bound/upper_best.pt"
)

# Disable joint learning
text = text.replace(
    "EPOCHS_JOINT = 15",
    "EPOCHS_JOINT = 0"
)

# Save and exit after Approach 1
old = """
    results['Approach 1'] = validate(model_fixed, test_loader, physics, theta, Config.INNER_STEPS, mode="hoag")
    print(f"Approach 1 Score: {results['Approach 1']:.4f}")
"""

new = """
    results['Approach 1'] = validate(model_fixed, test_loader, physics, theta, Config.INNER_STEPS, mode="hoag")
    print(f"Approach 1 Score: {results['Approach 1']:.4f}")

    torch.save(
        {
            'theta': theta.detach().cpu(),
            'score': results['Approach 1']
        },
        os.path.join(
            Config.OUTPUT_DIR,
            'foe_fixed_task_theta_only.pth'
        )
    )

    print("Saved FoE fixed-task result")
    return
"""

text = text.replace(old, new)

with open(file_path, "w") as f:
    f.write(text)

print("FoE fixed-task patch applied.")

!grep "UPPER_BOUND_CKPT" /content/bl_of_tar/mnist_bilevel_learning/mnist_foe/main.py
!grep "EPOCHS_JOINT" /content/bl_of_tar/mnist_bilevel_learning/mnist_foe/main.py

from PIL import Image

# Load image
img = Image.open("Screenshot_6.png")   # Change to your image path

# Resize to 256x256
img = img.resize((256, 256), Image.Resampling.LANCZOS)

# Save resized image
img.save("/content/output_image.png")

print("Image resized and saved successfully.")
